### ISSUE TITLE
docker_test  not working yet

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#26]
```
	// assert engine.images_list() == []
	// assert engine.containers_list() == []
	
```

get .../crystaluniverse/vlang_tools/vlang_tools/docker/docker_test.v to work

**Comment by Hamdy** [comment]
- Please make sure you are in development branch
- `cd examples && v run docker_example.v`
This is sample output from my ubuntu machine

![image](https://user-images.githubusercontent.com/526328/106580587-beeb2980-654a-11eb-8a5f-704fbe5bf612.png)

docker on remote machine not working yet due to (memory issue) we are still having and V team is working on it!

@despiegk please confirm it's working with you and please issue if it works

**Comment by Hamdy** [comment]
- [x] works fine now with new process module
- [x] find free port is now  finding non used range between 20000-40000 then gets random port from this range to reduce conflicts
