### ISSUE TITLE
digital twin can show wiki & websites which are build

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#29]
![image](https://user-images.githubusercontent.com/6021844/107140941-e57fda80-6925-11eb-874c-4c59df76060a.png)

before doing this first use the build function so all wiki's & websites are published

to run

```bash
v run install_publisher.v digitaltwin
```

- will install digital twin in code & run

todo

- make sure the digital twin exposes wike & build websites
- also errors need to be shown (use template)

**Comment by despiegk** [comment]
hypercore drive or local path, needs to be part of config file

need to be able to add multiple paths

e.g. 1 path on hyperdrive, 1 path on normal filesystem

**Comment by Hamdy** [comment]
- [X]  hyperdrive aliases (names) are now supported as well as ids
- [X] reading errors from json file
- [X] Serve static websites in nodejs with hyperdrive
   - PS: It does not show the website because I use custom root URL per each site i.e /drive/{drive_id}/www_threefold_farming and since this prefix is not compiled with the website, it shows 404 
  however, we had same behavior with old publishing tools and this behavior disappears when running after reverse proxy
- [ ] Serve wikis and sites from local file system
- [ ] Implement  a way to distinguish between websites and wikis
- [ ] load from Configuration 
- [ ] reload configuration and dynamic additions of new websites
